### ISSUE TITLE
部分内容转载请注明原文章地址

### ISSUE THREAD

**Issue by wuhan005** [AabyssZG/Open-Source-Information-Leakage#1]
我就说咋越看越熟悉，请注明转载地址：

<img width="1700" alt="image" src="https://github.com/AabyssZG/Open-Source-Information-Leakage/assets/12731778/a262098f-8cfe-4caa-8df7-b93aa3c6b839">

```
Light Cube - 《简单地聊聊 GitHub 信息泄露监控》 https://github.red/github-data-leak-talking/
```

**Comment by AabyssZG** [comment]
抱歉，之前做笔记的时候看过这篇文章，感觉概况的挺好的，就拿下来了😂
当时没找到原文地址，感谢师傅的isuess，这就加上哈哈😃

**Comment by AabyssZG** [comment]
师傅，已经加上啦🙂
有啥问题欢迎继续提Issues，也欢迎提交PR一起维护项目呀哈哈😘
